// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extension/rg.proto

package rg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Name                 string   `protobuf:"bytes,810001,opt,name=name,proto3" json:"name,omitempty"`
	HttpStatus           int32    `protobuf:"varint,810002,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	GrpcStatus           int32    `protobuf:"varint,810003,opt,name=grpc_status,json=grpcStatus,proto3" json:"grpc_status,omitempty"`
	OtherStatus          int32    `protobuf:"varint,810004,opt,name=other_status,json=otherStatus,proto3" json:"other_status,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,810005,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_26ed9f0d038c558a, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Error) GetHttpStatus() int32 {
	if m != nil {
		return m.HttpStatus
	}
	return 0
}

func (m *Error) GetGrpcStatus() int32 {
	if m != nil {
		return m.GrpcStatus
	}
	return 0
}

func (m *Error) GetOtherStatus() int32 {
	if m != nil {
		return m.OtherStatus
	}
	return 0
}

func (m *Error) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Auth struct {
	Enabled              bool     `protobuf:"varint,821001,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Roles                string   `protobuf:"bytes,821002,opt,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_26ed9f0d038c558a, []int{1}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Auth) GetRoles() string {
	if m != nil {
		return m.Roles
	}
	return ""
}

var E_Errors = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: ([]*Error)(nil),
	Field:         810000,
	Name:          "rg.errors",
	Tag:           "bytes,810000,rep,name=errors",
	Filename:      "extension/rg.proto",
}

var E_Auth = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Auth)(nil),
	Field:         811000,
	Name:          "rg.auth",
	Tag:           "bytes,811000,opt,name=auth",
	Filename:      "extension/rg.proto",
}

var E_GatewayUrl = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         812000,
	Name:          "rg.gateway_url",
	Tag:           "bytes,812000,opt,name=gateway_url",
	Filename:      "extension/rg.proto",
}

func init() {
	proto.RegisterType((*Error)(nil), "rg.error")
	proto.RegisterType((*Auth)(nil), "rg.Auth")
	proto.RegisterExtension(E_Errors)
	proto.RegisterExtension(E_Auth)
	proto.RegisterExtension(E_GatewayUrl)
}

func init() {
	proto.RegisterFile("extension/rg.proto", fileDescriptor_26ed9f0d038c558a)
}

var fileDescriptor_26ed9f0d038c558a = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0xe9, 0xbd, 0x6d, 0x6f, 0x3b, 0xe9, 0xdd, 0x04, 0x91, 0xd0, 0x85, 0xc4, 0x8a, 0xd0,
	0x4d, 0x27, 0xb6, 0xee, 0x22, 0x08, 0xd5, 0x75, 0x11, 0x22, 0x6e, 0xdc, 0x94, 0x49, 0x7b, 0x9c,
	0x04, 0xd2, 0x4c, 0x38, 0x33, 0x83, 0xfa, 0x08, 0xba, 0x10, 0xff, 0x3e, 0x87, 0xdb, 0xee, 0x5c,
	0xfa, 0x1a, 0x3e, 0x86, 0x4b, 0x99, 0x49, 0xe2, 0xb6, 0xcb, 0xf9, 0x9d, 0xdf, 0xf9, 0xf8, 0x38,
	0x0c, 0x71, 0xe1, 0x46, 0x41, 0x2e, 0x53, 0x91, 0x07, 0xc8, 0x69, 0x81, 0x42, 0x09, 0xf7, 0x0f,
	0xf2, 0xbe, 0xcf, 0x85, 0xe0, 0x19, 0x04, 0x96, 0xc4, 0xfa, 0x2a, 0x58, 0x82, 0x5c, 0x60, 0x5a,
	0x28, 0x81, 0xa5, 0x35, 0x78, 0x6f, 0x90, 0x16, 0x20, 0x0a, 0x74, 0xb7, 0x48, 0x33, 0x67, 0x2b,
	0xf0, 0x9e, 0xd6, 0x63, 0xbf, 0x31, 0xec, 0x46, 0xf6, 0xe5, 0xee, 0x12, 0x27, 0x51, 0xaa, 0x98,
	0x4b, 0xc5, 0x94, 0x96, 0xde, 0xb3, 0x1d, 0xb6, 0x22, 0x62, 0xe0, 0xb9, 0x65, 0x46, 0xe1, 0x58,
	0x2c, 0x6a, 0xe5, 0xa5, 0x56, 0x0c, 0xac, 0x94, 0x3d, 0xd2, 0x13, 0x2a, 0x01, 0xac, 0x9d, 0xd7,
	0xca, 0x71, 0x2c, 0xad, 0xa4, 0x7d, 0xf2, 0xdf, 0x36, 0x99, 0xaf, 0x40, 0x4a, 0xc6, 0xc1, 0x7b,
	0xab, 0x9a, 0xf4, 0x2c, 0x9e, 0x95, 0x74, 0x10, 0x92, 0xe6, 0x54, 0xab, 0xc4, 0xed, 0x93, 0x7f,
	0x90, 0xb3, 0x38, 0x83, 0xa5, 0x77, 0xf7, 0x30, 0xf1, 0x1b, 0xc3, 0x4e, 0x54, 0x03, 0x77, 0x9b,
	0xb4, 0x50, 0x64, 0x20, 0xbd, 0x7b, 0x3b, 0xe9, 0x46, 0xe5, 0x33, 0x3c, 0x25, 0x6d, 0x9b, 0x25,
	0xdd, 0x1d, 0x5a, 0x9e, 0x86, 0xd6, 0xa7, 0xa1, 0x33, 0x50, 0x89, 0x58, 0x9e, 0x15, 0x2a, 0x15,
	0xb9, 0xf4, 0x1e, 0xd7, 0x63, 0xff, 0xef, 0xd0, 0x99, 0x74, 0x29, 0x72, 0x6a, 0x77, 0xa2, 0x6a,
	0x35, 0x3c, 0x26, 0x4d, 0x66, 0x0a, 0x6c, 0x8a, 0xf8, 0xfe, 0x30, 0xf5, 0x9d, 0x49, 0xc7, 0x44,
	0x98, 0xca, 0x91, 0xdd, 0x0b, 0xa7, 0xc4, 0xe1, 0x4c, 0xc1, 0x35, 0xbb, 0x9d, 0x6b, 0xcc, 0x36,
	0xc6, 0x7c, 0x7d, 0x96, 0x57, 0x20, 0xd5, 0xd2, 0x05, 0x66, 0x27, 0x07, 0x97, 0x94, 0xa7, 0x2a,
	0xd1, 0x31, 0x5d, 0x88, 0x55, 0x80, 0x9a, 0xe5, 0x7c, 0xc4, 0x35, 0xea, 0x00, 0xf9, 0x88, 0x43,
	0x6e, 0x93, 0x82, 0xdf, 0x3f, 0x71, 0x84, 0x3c, 0x6e, 0x5b, 0x76, 0xf8, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xae, 0x9a, 0xb7, 0x79, 0x2a, 0x02, 0x00, 0x00,
}
