// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stitcher/stitcher.proto

package stitcher

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Extend struct {
	MessageType          string   `protobuf:"bytes,861001,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Extend) Reset()         { *m = Extend{} }
func (m *Extend) String() string { return proto.CompactTextString(m) }
func (*Extend) ProtoMessage()    {}
func (*Extend) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d87ad0535346e0f, []int{0}
}

func (m *Extend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extend.Unmarshal(m, b)
}
func (m *Extend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extend.Marshal(b, m, deterministic)
}
func (m *Extend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extend.Merge(m, src)
}
func (m *Extend) XXX_Size() int {
	return xxx_messageInfo_Extend.Size(m)
}
func (m *Extend) XXX_DiscardUnknown() {
	xxx_messageInfo_Extend.DiscardUnknown(m)
}

var xxx_messageInfo_Extend proto.InternalMessageInfo

func (m *Extend) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

type Service struct {
	MethodName           string   `protobuf:"bytes,871001,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Args                 string   `protobuf:"bytes,871002,opt,name=args,proto3" json:"args,omitempty"`
	Parameter            string   `protobuf:"bytes,871003,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Bulk                 bool     `protobuf:"varint,871004,opt,name=bulk,proto3" json:"bulk,omitempty"`
	ResolveIf            string   `protobuf:"bytes,871005,opt,name=resolve_if,json=resolveIf,proto3" json:"resolve_if,omitempty"`
	ReturnType           string   `protobuf:"bytes,871006,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	ServiceName          string   `protobuf:"bytes,871007,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	GoPackage            string   `protobuf:"bytes,871008,opt,name=go_package,json=goPackage,proto3" json:"go_package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d87ad0535346e0f, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *Service) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *Service) GetParameter() string {
	if m != nil {
		return m.Parameter
	}
	return ""
}

func (m *Service) GetBulk() bool {
	if m != nil {
		return m.Bulk
	}
	return false
}

func (m *Service) GetResolveIf() string {
	if m != nil {
		return m.ResolveIf
	}
	return ""
}

func (m *Service) GetReturnType() string {
	if m != nil {
		return m.ReturnType
	}
	return ""
}

func (m *Service) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Service) GetGoPackage() string {
	if m != nil {
		return m.GoPackage
	}
	return ""
}

type Field struct {
	Value                string   `protobuf:"bytes,881001,opt,name=value,proto3" json:"value,omitempty"`
	Source               string   `protobuf:"bytes,881002,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d87ad0535346e0f, []int{2}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Field) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type Resolver struct {
	Method               string   `protobuf:"bytes,811001,opt,name=method,proto3" json:"method,omitempty"`
	ServiceName          string   `protobuf:"bytes,811002,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ResolveIf            string   `protobuf:"bytes,811003,opt,name=resolve_if,json=resolveIf,proto3" json:"resolve_if,omitempty"`
	Root                 bool     `protobuf:"varint,811004,opt,name=root,proto3" json:"root,omitempty"`
	ReturnType           string   `protobuf:"bytes,811005,opt,name=return_type,json=returnType,proto3" json:"return_type,omitempty"`
	Timeout              int32    `protobuf:"varint,811006,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resolver) Reset()         { *m = Resolver{} }
func (m *Resolver) String() string { return proto.CompactTextString(m) }
func (*Resolver) ProtoMessage()    {}
func (*Resolver) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d87ad0535346e0f, []int{3}
}

func (m *Resolver) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resolver.Unmarshal(m, b)
}
func (m *Resolver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resolver.Marshal(b, m, deterministic)
}
func (m *Resolver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resolver.Merge(m, src)
}
func (m *Resolver) XXX_Size() int {
	return xxx_messageInfo_Resolver.Size(m)
}
func (m *Resolver) XXX_DiscardUnknown() {
	xxx_messageInfo_Resolver.DiscardUnknown(m)
}

var xxx_messageInfo_Resolver proto.InternalMessageInfo

func (m *Resolver) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Resolver) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Resolver) GetResolveIf() string {
	if m != nil {
		return m.ResolveIf
	}
	return ""
}

func (m *Resolver) GetRoot() bool {
	if m != nil {
		return m.Root
	}
	return false
}

func (m *Resolver) GetReturnType() string {
	if m != nil {
		return m.ReturnType
	}
	return ""
}

func (m *Resolver) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type Temp struct {
	Name                 string   `protobuf:"bytes,822001,opt,name=name,proto3" json:"name,omitempty"`
	Method               string   `protobuf:"bytes,822002,opt,name=method,proto3" json:"method,omitempty"`
	ServiceName          string   `protobuf:"bytes,822003,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Key                  string   `protobuf:"bytes,822004,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Temp) Reset()         { *m = Temp{} }
func (m *Temp) String() string { return proto.CompactTextString(m) }
func (*Temp) ProtoMessage()    {}
func (*Temp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d87ad0535346e0f, []int{4}
}

func (m *Temp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Temp.Unmarshal(m, b)
}
func (m *Temp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Temp.Marshal(b, m, deterministic)
}
func (m *Temp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Temp.Merge(m, src)
}
func (m *Temp) XXX_Size() int {
	return xxx_messageInfo_Temp.Size(m)
}
func (m *Temp) XXX_DiscardUnknown() {
	xxx_messageInfo_Temp.DiscardUnknown(m)
}

var xxx_messageInfo_Temp proto.InternalMessageInfo

func (m *Temp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Temp) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Temp) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Temp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Service)(nil),
	Field:         840001,
	Name:          "stitcher.service",
	Tag:           "bytes,840001,opt,name=service",
	Filename:      "stitcher/stitcher.proto",
}

var E_FieldExtend = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Extend)(nil),
	Field:         841002,
	Name:          "stitcher.field_extend",
	Tag:           "bytes,841002,opt,name=field_extend",
	Filename:      "stitcher/stitcher.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Field)(nil),
	Field:         841003,
	Name:          "stitcher.field",
	Tag:           "bytes,841003,opt,name=field",
	Filename:      "stitcher/stitcher.proto",
}

var E_ResolveMapper = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         841004,
	Name:          "stitcher.resolve_mapper",
	Tag:           "bytes,841004,opt,name=resolve_mapper",
	Filename:      "stitcher/stitcher.proto",
}

var E_Resolver = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Resolver)(nil),
	Field:         841005,
	Name:          "stitcher.resolver",
	Tag:           "bytes,841005,opt,name=resolver",
	Filename:      "stitcher/stitcher.proto",
}

var E_TempDatas = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: ([]*Temp)(nil),
	Field:         841006,
	Name:          "stitcher.temp_datas",
	Tag:           "bytes,841006,rep,name=temp_datas",
	Filename:      "stitcher/stitcher.proto",
}

var E_Root = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         851001,
	Name:          "stitcher.root",
	Tag:           "varint,851001,opt,name=root",
	Filename:      "stitcher/stitcher.proto",
}

var E_Request = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         851002,
	Name:          "stitcher.request",
	Tag:           "varint,851002,opt,name=request",
	Filename:      "stitcher/stitcher.proto",
}

var E_Extend = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*Extend)(nil),
	Field:         851003,
	Name:          "stitcher.extend",
	Tag:           "bytes,851003,opt,name=extend",
	Filename:      "stitcher/stitcher.proto",
}

func init() {
	proto.RegisterType((*Extend)(nil), "stitcher.Extend")
	proto.RegisterType((*Service)(nil), "stitcher.Service")
	proto.RegisterType((*Field)(nil), "stitcher.Field")
	proto.RegisterType((*Resolver)(nil), "stitcher.Resolver")
	proto.RegisterType((*Temp)(nil), "stitcher.Temp")
	proto.RegisterExtension(E_Service)
	proto.RegisterExtension(E_FieldExtend)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_ResolveMapper)
	proto.RegisterExtension(E_Resolver)
	proto.RegisterExtension(E_TempDatas)
	proto.RegisterExtension(E_Root)
	proto.RegisterExtension(E_Request)
	proto.RegisterExtension(E_Extend)
}

func init() { proto.RegisterFile("stitcher/stitcher.proto", fileDescriptor_0d87ad0535346e0f) }

var fileDescriptor_0d87ad0535346e0f = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xc7, 0xd5, 0xaf, 0xcd, 0xed, 0xa4, 0x5f, 0x01, 0xab, 0x82, 0x51, 0x25, 0x68, 0x08, 0x9b,
	0x6e, 0x9a, 0x88, 0x86, 0x2e, 0x70, 0x85, 0x90, 0x10, 0x54, 0x42, 0xd0, 0x16, 0x99, 0xae, 0xd8,
	0x44, 0x93, 0xe4, 0xc4, 0xb5, 0x1a, 0x7b, 0xcc, 0x78, 0x5c, 0xd1, 0x2d, 0xcf, 0x00, 0x2f, 0xc0,
	0xb2, 0x5c, 0xf6, 0xc0, 0xa2, 0x62, 0x83, 0xc4, 0x23, 0x70, 0x47, 0xec, 0x60, 0xc7, 0x65, 0x51,
	0xae, 0x42, 0x73, 0x4b, 0x42, 0xab, 0xca, 0xec, 0x7c, 0x2e, 0xff, 0x9f, 0xff, 0x33, 0xe7, 0xd8,
	0x70, 0x24, 0x11, 0x81, 0x68, 0xaf, 0x21, 0xaf, 0xdb, 0x87, 0x5a, 0xcc, 0x99, 0x60, 0x4e, 0xd1,
	0xc6, 0x53, 0x15, 0x9f, 0x31, 0xbf, 0x87, 0x75, 0x95, 0x6f, 0xa5, 0xdd, 0x7a, 0x07, 0x93, 0x36,
	0x0f, 0x62, 0xc1, 0x4c, 0x6f, 0x75, 0x16, 0xf2, 0x17, 0x6e, 0x08, 0x8c, 0x3a, 0xce, 0x09, 0x18,
	0x0f, 0x31, 0x49, 0xa8, 0x8f, 0x4d, 0xb1, 0x19, 0x23, 0x79, 0xf6, 0xf4, 0x54, 0x65, 0x64, 0xa6,
	0xe4, 0x95, 0x4d, 0x76, 0x75, 0x33, 0xc6, 0xea, 0xcd, 0xff, 0xa0, 0x70, 0x15, 0xf9, 0x46, 0xd0,
	0x46, 0xe7, 0x38, 0x94, 0x43, 0x14, 0x6b, 0xac, 0xd3, 0x8c, 0x68, 0x88, 0xe4, 0xf9, 0xad, 0x79,
	0xd5, 0x0f, 0x3a, 0xb9, 0x4c, 0x43, 0x74, 0x26, 0x61, 0x8c, 0x72, 0x3f, 0x21, 0x2f, 0x4c, 0x4d,
	0x45, 0xce, 0x31, 0x28, 0xc5, 0x94, 0xd3, 0x10, 0x05, 0x72, 0xf2, 0xd2, 0x94, 0x06, 0x29, 0xa9,
	0x6a, 0xa5, 0xbd, 0x75, 0xf2, 0x4a, 0x95, 0x8a, 0x9e, 0x8a, 0x9c, 0x69, 0x00, 0x8e, 0x09, 0xeb,
	0x6d, 0x60, 0x33, 0xe8, 0x92, 0xd7, 0x56, 0x66, 0x72, 0x17, 0xbb, 0xd2, 0x0f, 0x47, 0x91, 0xf2,
	0x48, 0xfb, 0x7f, 0x63, 0xfd, 0xe8, 0xa4, 0xb4, 0x2f, 0xcf, 0x98, 0x68, 0xf7, 0xda, 0xf3, 0x5b,
	0xd3, 0x53, 0x36, 0x59, 0x65, 0x7a, 0x1a, 0xc0, 0x67, 0xcd, 0x98, 0xb6, 0xd7, 0xa9, 0x8f, 0xe4,
	0x9d, 0x7d, 0x91, 0xcf, 0xae, 0xe8, 0x54, 0xf5, 0x34, 0xe4, 0x16, 0x03, 0xec, 0x75, 0x9c, 0xc3,
	0x90, 0xdb, 0xa0, 0xbd, 0x14, 0xc9, 0x87, 0xf7, 0xba, 0x49, 0x87, 0x0e, 0x81, 0x7c, 0xc2, 0x52,
	0xde, 0x46, 0xf2, 0xd1, 0x14, 0x4c, 0x5c, 0xdd, 0x1e, 0x81, 0xa2, 0xa7, 0x1d, 0x73, 0xd9, 0xa6,
	0xef, 0x8a, 0x7c, 0xdb, 0x3e, 0xa9, 0xdb, 0x74, 0xbc, 0xc7, 0xe7, 0x77, 0x53, 0xdf, 0xed, 0x73,
	0xe8, 0x42, 0x7e, 0x98, 0x96, 0xa1, 0x0b, 0x99, 0x84, 0x31, 0xce, 0x98, 0x20, 0x3f, 0x55, 0xa9,
	0xe8, 0xa9, 0x68, 0xf7, 0x35, 0xfd, 0x32, 0xba, 0xe1, 0x6b, 0x9a, 0x82, 0x82, 0x08, 0x42, 0x64,
	0xa9, 0x20, 0xbf, 0x55, 0x39, 0xe7, 0xd9, 0x44, 0x95, 0xc1, 0xd8, 0x2a, 0x86, 0xb1, 0x84, 0x2b,
	0x6b, 0x9f, 0x6e, 0xcf, 0xe9, 0xd1, 0xca, 0x68, 0xe8, 0x48, 0x9f, 0x4d, 0x7e, 0xbf, 0x23, 0x7d,
	0x31, 0xf5, 0xbf, 0x8e, 0xe4, 0xc0, 0xe8, 0x3a, 0x6e, 0x92, 0xaf, 0xa6, 0x26, 0x03, 0xf7, 0x32,
	0x14, 0x4c, 0x8b, 0x73, 0xb4, 0xa6, 0xf7, 0xb9, 0x66, 0xf7, 0xb9, 0xa6, 0xe6, 0xb0, 0x12, 0x8b,
	0x80, 0x45, 0x09, 0x79, 0x72, 0xa7, 0x51, 0x19, 0x99, 0x29, 0xcf, 0x1d, 0xaa, 0xf5, 0x3f, 0x08,
	0xb3, 0xab, 0x9e, 0x45, 0xb8, 0xab, 0x30, 0xde, 0x95, 0x9a, 0x26, 0xea, 0xad, 0xcf, 0x40, 0x6e,
	0x6d, 0x69, 0xe4, 0xc1, 0x01, 0x52, 0x7f, 0x2e, 0x5e, 0x59, 0x61, 0x74, 0xe0, 0x2e, 0x42, 0x4e,
	0x85, 0x59, 0xb8, 0xbb, 0x06, 0x77, 0x60, 0x80, 0x53, 0x75, 0x4f, 0xcb, 0xdd, 0x45, 0x98, 0xb0,
	0x23, 0x0d, 0x69, 0x1c, 0x23, 0xcf, 0x02, 0xde, 0x53, 0xc0, 0x92, 0xf7, 0xbf, 0x91, 0x2d, 0x29,
	0x95, 0xbb, 0x02, 0x45, 0x6e, 0xb7, 0x2c, 0x83, 0x70, 0xdf, 0x58, 0x72, 0x06, 0x96, 0xec, 0x82,
	0x7a, 0x7d, 0x88, 0xbb, 0x0c, 0x20, 0x30, 0x8c, 0x9b, 0x1d, 0x2a, 0x68, 0x92, 0x85, 0x7c, 0xb0,
	0xd5, 0xa8, 0x8c, 0xce, 0x94, 0xe7, 0x26, 0x06, 0x48, 0xb9, 0x32, 0x5e, 0x49, 0x22, 0xce, 0x4b,
	0x82, 0x3b, 0xaf, 0x57, 0xd3, 0x99, 0xde, 0x43, 0x5a, 0xd2, 0x7f, 0x1b, 0xcb, 0x7a, 0xb8, 0xd3,
	0x18, 0xec, 0xae, 0xbb, 0x00, 0x05, 0x8e, 0xd7, 0x53, 0x4c, 0xfe, 0x41, 0xf9, 0xc8, 0x28, 0xad,
	0xc2, 0xbd, 0x04, 0x79, 0x33, 0xf4, 0x4c, 0xed, 0xe3, 0x9d, 0xfd, 0xc6, 0x6e, 0x10, 0xe7, 0xce,
	0x5e, 0x3b, 0xe3, 0x07, 0x62, 0x2d, 0x6d, 0xd5, 0xda, 0x2c, 0xac, 0xf3, 0x94, 0x46, 0xfe, 0xac,
	0x9f, 0xf2, 0xb4, 0xce, 0xfd, 0x59, 0x1f, 0x23, 0x05, 0xae, 0xab, 0xde, 0x24, 0x60, 0x51, 0xff,
	0x0f, 0xbd, 0x60, 0x1f, 0x5a, 0x79, 0xd5, 0xd2, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xcf,
	0x89, 0x44, 0xc6, 0x05, 0x00, 0x00,
}
